# Anchor 0.30.1 requiere nightly de este rango O stable >=1.80.
# Usamos stable 1.81.0 que es la versión mínima probada con anchor-lang 0.30.1
# y compatible con solana-program 1.18.x que trae el container backpackapp/build:v0.30.1.
[toolchain]
channel    = "1.81.0"
components = ["rustfmt", "clippy"]
targets    = ["bpfel-unknown-unknown"]
